<a href="https://colab.research.google.com/github/sbanty/Scipy-computing/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#Load the data

from google.colab import files
cnt_auction_df = files.upload()

Saving carbon_nanotubes.csv to carbon_nanotubes (1).csv

In [ ]:
type(cnt_auction_df)
cnt_auction_df = pd.read_csv('carbon_nanotubes.csv')

In [ ]:
cnt = pd.DataFrame.from_dict(cnt_auction_df,orient = 'columns')
#cnt = pd.DataFrame.from_dict(ipl_auction_df, 10)
print(cnt)
type(cnt)

                                                     Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'
2;1;0  679005;0 701318;0 017033;0 721039;0 730232;0                                            17014.0
       717298;0 642129;0 231319;0 738414;0 65675;0                                            232369.0
       489336;0 303751;0 088462;0 477676;0 263221;0                                            88712.0
       413957;0 632996;0 040843;0 408823;0 657897;0                                            39796.0
       334292;0 543401;0 15989;0  303349;0 558807;0                                           157373.0
...                                                                                                ...
12;6;0 834201;0 399891;0 89127;0  841858;0 405882;0                                           891356.0
       698374;0 24471;0  962699;0 706555;0 248416;0                                           962833.0
       923823;0 568913;0 819842;0 929403;0 576284;0                                           819879.0
       934978;0 602319;0 938889;0 941844;0 610608;0                                           938755.0
       953664;0 698374;0 962699;0 961243;0 707812;0                                           962605.0

[10721 rows x 1 columns]

pandas.core.frame.DataFrame

In [ ]:
pd.set_option('display.max_columns',15)
cnt_auction_df.head(6)

                                                    Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'
2;1;0 679005;0 701318;0 017033;0 721039;0 730232;0                                            17014.0
      717298;0 642129;0 231319;0 738414;0 65675;0                                            232369.0
      489336;0 303751;0 088462;0 477676;0 263221;0                                            88712.0
      413957;0 632996;0 040843;0 408823;0 657897;0                                            39796.0
      334292;0 543401;0 15989;0  303349;0 558807;0                                           157373.0
      510664;0 696249;0 255128;0 496977;0 725608;0                                            25597.0

In [ ]:
list(cnt_auction_df.columns)

["Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'"]

In [ ]:
print(list(cnt.columns))
list(cnt.columns)
cnt.columns

["Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'"]

Index(['Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w''], dtype='object')

In [ ]:
cnt_auction_df.head(5).transpose()

                                                      2;1;0            \
                                                   679005;0  717298;0
                                                   701318;0  642129;0
                                                   017033;0  231319;0
                                                   721039;0  738414;0
                                                   730232;0   65675;0
Chiral indice n;Chiral indice m;Initial atomic ...  17014.0  232369.0


                                                   489336;0 413957;0  334292;0
                                                   303751;0 632996;0  543401;0
                                                   088462;0 040843;0   15989;0
                                                   477676;0 408823;0  303349;0
                                                   263221;0 657897;0  558807;0
Chiral indice n;Chiral indice m;Initial atomic ...  88712.0  39796.0  157373.0

In [ ]:
cnt_auction_df.shape
cnt_auction_df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 10721 entries, ('2;1;0', '679005;0', '701318;0', '017033;0', '721039;0', '730232;0') to ('12;6;0', '953664;0', '698374;0', '962699;0', '961243;0', '707812;0')
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                  Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                  --------------  -----
 0   Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'  10700 non-null  float64
dtypes: float64(1)
memory usage: 1.5+ MB

In [ ]:
cnt_auction_df[0:6]

                                                    Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'
2;1;0 679005;0 701318;0 017033;0 721039;0 730232;0                                            17014.0
      717298;0 642129;0 231319;0 738414;0 65675;0                                            232369.0
      489336;0 303751;0 088462;0 477676;0 263221;0                                            88712.0
      413957;0 632996;0 040843;0 408823;0 657897;0                                            39796.0
      334292;0 543401;0 15989;0  303349;0 558807;0                                           157373.0
      510664;0 696249;0 255128;0 496977;0 725608;0                                            25597.0

In [ ]:
cnt_auction_df[-6:]

                                                     Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w'
12;6;0 876454;0 467139;0 796032;0 882181;0 473901;0                                           796005.0
       834201;0 399891;0 89127;0  841858;0 405882;0                                           891356.0
       698374;0 24471;0  962699;0 706555;0 248416;0                                           962833.0
       923823;0 568913;0 819842;0 929403;0 576284;0                                           819879.0
       934978;0 602319;0 938889;0 941844;0 610608;0                                           938755.0
       953664;0 698374;0 962699;0 961243;0 707812;0                                           962605.0

In [ ]:
cnt_auction_df['TDNsa3VOcsBG'][0:5]

KeyError: 'TDNsa3VOcsBG'

In [ ]:
print(cnt_auction_df.columns)

Index(['Chiral indice n;Chiral indice m;Initial atomic coordinate u;Initial atomic coordinate v;Initial atomic coordinate w;Calculated atomic coordinates u';Calculated atomic coordinates v';Calculated atomic coordinates w''], dtype='object')